name: ps_shakib
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio: ^5.8.0+1
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  # Riverpod annotations
  riverpod_annotation: ^2.6.1

  # Routing and navigation
  go_router: ^16.0.0

  #Freezed annotation
  freezed_annotation: ^2.4.4
  #Json annotation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  riverpod_generator: ^2.6.2
  build_runner: ^2.5.4
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
